"""adding verification

Revision ID: 114390ac5e5c
Revises: 29efb3b21846
Create Date: 2024-02-23 16:51:43.314977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114390ac5e5c'
down_revision = '29efb3b21846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
