"""adding feedback

Revision ID: 29efb3b21846
Revises: c706c566d037
Create Date: 2024-02-22 14:32:01.646094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29efb3b21846'
down_revision = 'c706c566d037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
